name: flyanalysis-env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - scipy
  - opencv
  - pyarrow
  - tqdm
  - ipython
  - jupyter
  - pip
  - pybind11
  - spatialmath-python
  - seaborn
  - statsmodels
  - pip:
    - pynumdiff
    - cvxpy[CBC,CVXOPT,GLOP,GLPK,GUROBI,MOSEK,PDLP,SCIP,XPRESS]
    - git+https://github.com/pychebfun/pychebfun.git