name: flyanalysis-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - scipy
  - opencv
  - pyarrow
  - tqdm
  - ipython
  - jupyter
  - pip
  - pybind11
  - spatialmath-python