name: flyanalysis-env

channels:
  - defaults
  - conda-forge

dependencies:
  - python<=3.11
  - pip
  - scipy
  - pandas
  - numpy
  - tqdm
  - natsort
  - jupyterlab
  - filterpy
  - ipympl
  - matplotlib
  - ipywidgets
  - sphinx
  - sphinx-rtd-theme
  - sphinx-autodoc-typehints
  - joblib
  - seaborn
  - pyarrow
  - spatialmath-python

  - pip:
    - opencv-contrib-python>4
    - pycircstat
    - nose

