name: flyanalysis-env

channels:
  - defaults
  - conda-forge

dependencies:
  - python>=3.10
  - pip
  - scipy
  - pandas
  - numpy
  - tqdm
  - natsort
  - jupyterlab
  - filterpy
  - ipympl
  - matplotlib
  - ipywidgets

  - pip:
    - opencv-contrib-python>4
    - pybind11_rdp
    - spatialmath-python
    - decord