name: flyanalysis-env

channels:
  - defaults
  - conda-forge

dependencies:
  - python
  - pip
  - scipy
  - pandas
  - numpy
  - tqdm
  - natsort
  - jupyterlab
  - filterpy
  - ipympl
  - matplotlib
  - seaborn
  - pyarrow
  - spatialmath-python
